// <auto-generated />
using CompanyOefening.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyOefening.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20220512203400_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompanyOefening.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DepartmentNr")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("DepartmentID");

                    b.ToTable("Departements");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            EmployeeId = 0,
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentID = 2,
                            EmployeeId = 0,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentID = 3,
                            EmployeeId = 0,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("CompanyOefening.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeNr ")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DepartmentId = 1,
                            Name = "Kenan Kurda",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeID = 2,
                            DepartmentId = 2,
                            Name = "Peral De Smet",
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("CompanyOefening.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProjectNr ")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            Name = ".Net Developer"
                        },
                        new
                        {
                            ProjectID = 2,
                            Name = "Java Developer"
                        });
                });

            modelBuilder.Entity("CompanyOefening.Models.Employee", b =>
                {
                    b.HasOne("CompanyOefening.Models.Department", "Department")
                        .WithOne("Employee")
                        .HasForeignKey("CompanyOefening.Models.Employee", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyOefening.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
